### ISSUE TITLE
Produce FSdcos Documentation for v0.1

### ISSUE THREAD

**Issue by HarryMcCarney** [fslaborg/Graphoscope#19] opened 2023-07-18 11:10 UTC
This should include section on creating graphs from edge lists and running basic operations and algorithms in an fsx environment.

**Comment by HarryMcCarney** [comment] 2023-07-23 21:39
Hi Kevin,

I have just released version 0.1.0. It seemed to work fine and the package is published to nuget. 

But I can't access the docs. The GH Action logs say they are published to https://fslab.org/Graphoscope/ but I get a 404 on that URL and on https://fslaborg.github.com/graphoscope/

I also made the repo public as it doesn't seem possible to use GH pages in a private repo, and now we have an initial version, I think its time. 

Please let me know how I can resolve this. 

thanks!
Harry

**Comment by kMutagene** [comment] 2023-07-24 04:40
It seems like you are pushing commits to gh-pages that are not on main. I would not recommend this. The workflow of publishing docs with the current repo setup should look like this:

- commit documentation on main (or another feature branch)
- from that branch, either release docs via the `releaseDocs` build target, or set up a github action that releases docs on commit.
- for both of these, gh-pages should be an orphan branch, meaning there are no other commits than genereated documentation. This is also why the current setup does not work. The pages and source files are on wrong paths on the current gh-pages branch

So, we can fix this via:
- moving all the documentation commits onto main (or v0.1, whatever is the current branch you want to publish docs for)
- delete the current gh-pages branch
- push a properempty  orphan branch to gh-pages
- release docs either via build target or github action

**Comment by kMutagene** [comment] 2023-07-24 04:42
So i'd suggest you move everything you added on gh-pages to your target branch and i'll take care of the rest

**Comment by kMutagene** [comment] 2023-07-24 09:01
It also seems like fsdocs artifacts ended up being committed to multiple branches. Looks like i forgot to add those to the gitignore

**Comment by kMutagene** [comment] 2023-07-24 11:13
@DoganCK Which command did you use to publish the current state of the docs and on which branch? I'll try to reproduce this locally.

**Comment by DoganCK** [comment] 2023-07-24 11:22
@kMutagene we used ./build.sh releaseDocs on the main branch. The locally generated output seems fine. But the documentation doesn't seems to update the `root` folder.

**Comment by kMutagene** [comment] 2023-07-24 11:27
However now it looks like the evaluators are not working, looking into it

**Comment by kMutagene** [comment] 2023-07-24 11:29
Oh, one of the reasons might be that this file is missing for me: 
```fsharp
let file = "C:/Projects/Doodles/out.moreno_rhesus_rhesus.txt"
```
can you commit that file to `/docs/data` ?

**Comment by DoganCK** [comment] 2023-07-24 11:44
Thanks @kMutagene !
here's the [file](https://github.com/fslaborg/Graphoscope/blob/main/docs/data/out.moreno_rhesus_rhesus.txt)

**Comment by kMutagene** [comment] 2023-07-24 11:52
Sorry i forgot the other one, the karate dataset is missing as well

**Comment by DoganCK** [comment] 2023-07-24 12:02
Added. https://github.com/fslaborg/Graphoscope/tree/main/docs/data

`zachary.txt` is the karate data

**Comment by kMutagene** [comment] 2023-07-24 12:20
I created 2 PRs that should fix any issues we currently see.

**Comment by DoganCK** [comment] 2023-07-24 13:52
Thanks @kMutagene !

**Closed by DoganCK** 2023-07-24 13:52 UTC
